services:

  pgsql_db:
    image: postgres:17
    container_name: fireme-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fireme_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    container_name: fireme-backend
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=pgsql_db
    depends_on:
      pgsql_db:
        condition: service_healthy
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fireme-frontend
    ports:
      - 4000:3000
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://192.168.1.119:8080
    depends_on:
      backend:
        condition: service_started

volumes:
  fireme_pgdata: